version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - "3010:80"
